sudo: required

services:
  - docker

script:
  - make run

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  target-branch: gh-pages